name: tests

on: [push, pull_request]

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.10'
      - name: Run static analysis
        run: |
          pip install pre-commit==2.15.0
          pre-commit run --all

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.10'
      - name: Install dependencies
        run: |
          pip install pytest
          pip install -e .
      - name: Run unit tests
        run: py.test